- name: Setup Yum repos
  ansible.builtin.shell: "{{item}}"
  loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbitmq and erlang
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server

- name: start the service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: adding user to rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: "{{SECRET.RABBITMQ_USER}}"
    password: "{{SECRET.RABBITMQ_PASS}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator




