- name: Install the latest version of golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: download content from git
  ansible.builtin.import_role:
    name: common
    tasks_from: download-from-git

- name: compalies golang dependinces
  ansible.builtin.command: "{{item}}"
  loop:
    - go mod init dispatch
    - go get
    - go build
  args:
    executable: go
    become_user: roboshop
    become: yes



