- name: adding roboshop user
  ansible.builtin.user:
    name: roboshop

- name: downloading and unzip {{COMPONENT}} file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: removing old contend
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy {{COMPONENT}}  file
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop