- name: Setup Yum repos
  ansible.builtin.shell: curl -s https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - maven
    state: installed

- name: download conent from git
  ansible.builtin.import_role:
    name: common
    tasks_from: download-from-git

- name: complies maveen dependices
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: import from common for systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd